custom: ${file(./env.yml)}

service: amazon-goldbox

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  stage: production
  environment:
    service: ${self:service}
    bucket: ${self:custom.bucket}
    feeds_path: ${self:provider.stage}/rss/feeds.json
    active_path: ${self:provider.stage}/rss/active.json
    rss_path: ${self:provider.stage}/rss/rss.xml
    affiliate_id: ${self:custom.affiliate_id}
    blacklist_path: ${self:custom.blacklist_path, ''}
    hashtags_path: ${self:custom.hashtags_path, ''}
    accounts_path: ${self:custom.accounts_path, ''}
    default_image_link: ${self:custom.default_image_link, ''}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:provider.environment.bucket}/*"

functions:
  feeds:
    handler: feeds.feeds
    events:
      - schedule: cron(50 9 * * ? *)
  rss:
    handler: rss.rss
    events:
      - schedule: cron(0/20 * * * ? *)
    environment:
      FMD_TWEET_APP_SECRET: ${self:custom.FMD_TWEET_APP_SECRET}
      FMD_TWITTER_CONSUMER_KEY: ${self:custom.FMD_TWITTER_CONSUMER_KEY}
      FMD_TWITTER_CONSUMER_SECRET: ${self:custom.FMD_TWITTER_CONSUMER_SECRET}
      FMD_TWITTER_ACCESS_TOKEN_KEY: ${self:custom.FMD_TWITTER_ACCESS_TOKEN_KEY}
      FMD_TWITTER_ACCESS_TOKEN_SECRET: ${self:custom.FMD_TWITTER_ACCESS_TOKEN_SECRET}

plugins:
  - serverless-offline
